{{- range .Values.repositories }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s" . | trunc 63 | trimSuffix "-" }}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/alanbruhns/{{ . }}
  name: {{ . }}
---
{{- end }}