{{- range .Values.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.environment }}-{{ . }}
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://github.com/alanbruhns/ldp-platform-values
    targetRevision: main
    ref: values
  - repoURL: https://github.com/alanbruhns/{{ . }}
    targetRevision: {{ default $.Values.environment | quote }}
    path:  helm
    helm:
      valueFiles:
      - $values/{{ $.Values.environment }}/{{ . }}.values.yaml
      values: |
        environment: {{ $.Values.environment }}        
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
