{{- range $appName, $appConfig := .Values.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.environment }}-{{ $appName }}
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://github.com/alanbruhns/ldp-platform-helm
    targetRevision: main
    ref: values
  - repoURL: {{ $appConfig.source.repoURL | quote }}
    targetRevision: {{ default $.Values.environment $appConfig.source.targetRevision | quote }}
    path:  {{ $appConfig.source.path  | quote }}
    helm:
      valueFiles:
      - $values/{{ default $.Values.environment $appConfig.source.targetRevision }}/{{ $appName }}.values.yaml
      values: |
        environment: {{ default $.Values.environment $appConfig.source.targetRevision }}        
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
