apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.environment }}-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/alanbruhns/ldp-platform-values.git
      revision: main
      files:
      - path: "{{ .Values.environment }}/ldp-api-*"
      values:
        appName: "{{ .path.filename }}"
  template:
    metadata:
      name: '{{ .Values.environment }}-ldp-api-identity'
    spec:
      project: default
      sources:
      - repoURL: https://github.com/alanbruhns/ldp-platform-values
        targetRevision: main
        ref: values
      - repoURL: https://github.com/alanbruhns/{{ .values.appName }}
        targetRevision: {{ .Values.environment | quote }}
        path:  helm
        helm:
          valueFiles:
          - $values/{{ .Values.environment }}/{{ .values.appName }}.values.yaml
          values: |
            environment: {{ .Values.environment }}        
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true