{{- range $envName, $envConfig := .Values.environments }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-{{ $envName }}
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://github.com/alanbruhns/ldp-platform-values
    targetRevision: main
    ref: values
  - repoURL: https://github.com/alanbruhns/ldp-platform-helm
    targetRevision: {{ $envName }}
    path: app-of-environments
    helm:
      valueFiles:
      - $values/{{ $envName }}/app-of-environments.values.yaml
      values: |
        environment: {{ $envName }}
  destination:
    server: {{ $envConfig.destination.server }}
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
