{{- range .Values.repositories }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ . | split "/" | index -1 | trunc 63 | trimSuffix "-" | quote }}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: {{ . | quote }}
  name: {{ . | split "/" | index -1 | quote }}  # Extract the last part of the URL
---
{{- end }}
